WebAppA02/Pages/CRUD.cshtml.cs
using Clubs.BLL;
using Clubs.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace WebAppA02.Pages
{
    public class CRUDModel : PageModel
    {
        #region Constructor Injection Depedency setup
        //create a variable to hang onto the injected service identifier
        private readonly EmployeesService _employeesService;
        private readonly ClubsService _clubsService;

        public CRUDModel(EmployeesService employeesService, ClubsService clubsService)
        {
            _employeesService = employeesService;
            _clubsService = clubsService;
        }
        #endregion
        [BindProperty(SupportsGet = true)]
        public string? clubid { get; set; }
        public string Feedback { get; set; }
        public bool HasFeedback { get { return !string.IsNullOrWhiteSpace(Feedback); } }

        [BindProperty]
        public Club clubInfo { get; set; }
        public List<Club> clubList { get; set; }

        public List<Employee> employeeList { get; set; }
        public void OnGet()
        {
            if (clubid != null)
            {
                clubInfo = _clubsService.Club_GetById(clubid);
            }

            PopulateLists();
        }

        public void PopulateLists()
        {
            clubList = _clubsService.Club_List();
            employeeList = _employeesService.Employee_List();
        }
        public IActionResult OnPost()
        {
            PopulateLists();
            return Page();
        }

        public IActionResult OnPostCancel()
        {
            return RedirectToPage("./Query");
        }
        public IActionResult OnPostInsert()
        {
            if (clubInfo.EmployeeID == 0) // if no staff is selected
            {
                ModelState.AddModelError(nameof(clubInfo.EmployeeID), "Select a staff for the club");
            }
            if (String.IsNullOrEmpty(clubInfo.ClubID))
            {
                ModelState.AddModelError(nameof(clubInfo.ClubID), "Input a ClubID");

            }
            if (String.IsNullOrEmpty(clubInfo.ClubName))
            {
                ModelState.AddModelError(nameof(clubInfo.ClubName), "ClubName cannot be empty.");

            }
            if (ModelState.IsValid)
            {
                try
                {
                    string newclubid = _clubsService.Club_AddClub(clubInfo);
                    Feedback = $"Club (id:{clubInfo.ClubID}) has been added to the system";
                    PopulateLists();
                }
                catch (ArgumentNullException ex)
                {
                    ModelState.AddModelError(nameof(clubInfo.ClubName), GetInnerException(ex).Message);
                    PopulateLists();
                    return Page();
                }
                catch (ArgumentException ex)
                {
                    ModelState.AddModelError(nameof(clubInfo.ClubName), GetInnerException(ex).Message);
                    PopulateLists();
                    return Page();
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(nameof(clubInfo.ClubName), GetInnerException(ex).Message);
                    PopulateLists();
                    return Page();
                }
            }
            else
            {

                PopulateLists();
            }

            return Page();
        }

        public IActionResult OnPostUpdate()
        {
            if (clubInfo.EmployeeID == 0)
            {
                ModelState.AddModelError(nameof(clubInfo.EmployeeID), "Select a club for the employee");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    int rowsaffected = _clubsService.Club_UpdateClub(clubInfo);
                    if (rowsaffected > 0)
                    {
                        Feedback = $"Club (id:{clubInfo.ClubID}) has been updated to the system";
                    }
                    else
                    {
                        Feedback = $"Club (id:{clubInfo.ClubID}) has been removed from the system. Return to the search page.";
                    }
                    PopulateLists();
                }
                catch (ArgumentNullException ex)
                {
                    ModelState.AddModelError(nameof(clubInfo.ClubName), GetInnerException(ex).Message);
                    PopulateLists();
                    return Page();
                }
                catch (ArgumentException ex)
                {
                    ModelState.AddModelError(nameof(clubInfo.ClubName), GetInnerException(ex).Message);
                    PopulateLists();
                    return Page();
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(nameof(clubInfo.ClubName), GetInnerException(ex).Message);
                    PopulateLists();
                    return Page();
                }
            }
            else
            {

                PopulateLists();
            }

            return Page();
        }
        public IActionResult OnPostDeactivate()
        {
            if (clubInfo.ClubID == null)
            {
                ModelState.AddModelError(nameof(clubInfo.ClubID), "Select a category for the product");
            }

            if (ModelState.IsValid)
            {
                try
                {

                    int rowsaffected = _clubsService.Club_DeactivateClub(clubInfo);
                    if (rowsaffected > 0)
                    {
                        Feedback = $"Club (id:{clubInfo.ClubID}) has been deactivate";
                    }


                    PopulateLists();

                }
                catch (ArgumentNullException ex)
                {
                    ModelState.AddModelError(nameof(clubInfo.ClubName), GetInnerException(ex).Message);
                    PopulateLists();
                    return Page();
                }
                catch (ArgumentException ex)
                {
                    ModelState.AddModelError(nameof(clubInfo.ClubName), GetInnerException(ex).Message);
                    PopulateLists();
                    return Page();
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(nameof(clubInfo.ClubName), GetInnerException(ex).Message);
                    PopulateLists();
                    return Page();
                }
            }
            else
            {
                PopulateLists();
            }

            return Page();
        }

        private Exception GetInnerException(Exception ex)
        {
            while (ex.InnerException != null)
            {
                ex = ex.InnerException;
            }
            return ex;
        }

    }
}

WebAppA02/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebAppA02.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebAppA02/Pages/Index.cshtml.cs
using Clubs.BLL;
using Clubs.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebAppA02.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        //create a variable to hang onto the injected service identifier
        private readonly ClubsService _clubsService;
        public IndexModel(ILogger<IndexModel> logger, ClubsService clubsService)
        {
            _logger = logger;
            _clubsService= clubsService;
        }

    }
}

WebAppA02/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebAppA02.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebAppA02/Pages/Query.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Clubs.BLL;
using Clubs.Entities;

namespace WebAppA02.Pages
{
    public class QueryModel : PageModel
    {
        #region Constructor Injection Depedency setup
        //create a variable to hang onto the injected service identifier
        private readonly EmployeesService _employeesService;
        private readonly ClubsService _clubsService;

        public QueryModel(EmployeesService employeesService, ClubsService clubsService)
        {
            _employeesService = employeesService;
            _clubsService= clubsService;
        }
        #endregion
        [BindProperty]
        public string clubStatus { get; set; }

        public List<Club> ClubList { get; set; }
        public List<Employee> EmployeeList { get; set; }

        public int CurrentPage { get; set; } = 1;

        public int TotalPages { get; set; }

   

        public void OnGet()
        {

        }
        public IActionResult OnPostSearch()
        {
            bool status = false;
            if (clubStatus == "Active")
            {
                status = true;
            }
            else if (clubStatus == "In-Active")
            {
                status = false;
            }
            ClubList = _clubsService.GetClubListByStatus(status);
            EmployeeList = _employeesService.GetEmployeeList();

            return Page();
        }
    }
}

WebAppA02/Pages/CRUD.cshtml
@page "{clubid?}"
@model WebAppA02.Pages.CRUDModel
@{
    ViewData["Title"] = "CRUD";
}
<h1>CRUD Page</h1>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

@if (Model.HasFeedback)
{
    <p>@Model.Feedback</p>
}

@if (ModelState.ErrorCount > 0)
{
    <div asp-validation-summary="All" class="alert alert-danger">
        <p>Please review concerns and correct:</p>
    </div>
}

<form method="post">
    <label>
        ID:
        @if(Model.clubInfo == null)
        {
            //the intent is a new product is being added to the database
            //there is no pkey value
            //the product entity in sql has an identity pkey
            <input type="text" asp-for="clubInfo.ClubID"  data-val="false" value="">
            
        }
        else
        {
            //the intent is to update /delete an existing product record on the database
            //therefore a pkey value will exist on the product info record
            //One does NOT want to mess with the pkey of a record
            //this piece of data should only be viewed and not alterable
            <input type="text" asp-for="clubInfo.ClubID" readonly data-val="false">
        }
        @*to be able to display an error associated with a field firectly adjcent to the input field, we can use a span tag with the asp-validation-for helper*@
        <span asp-validation-for="clubInfo.ClubID"></span>
    </label>
    <label>
        Club Name: 
        <input type="text" asp-for="clubInfo.ClubName" data-val="false" />
        <span asp-validation-for="clubInfo.ClubName"></span>
    </label>
@*    <label>
        Employee:
        <select asp-for="clubInfo.EmployeeID">
            <option value="0">select...</option>
            @foreach(var person in Model.employeeList)
            {
                
                <option value="@person.EmployeeID" selected=@(Model.clubInfo != null && person.EmployeeID == Model.clubInfo.EmployeeID)>
                    @person.FirstName @person.LastName
                </option>
            }
        </select>
        <span asp-validation-for="clubInfo.EmployeeID"></span>
    </label>*@
    <label>
        Employee:
        <input type="text" list="staffList" name="" asp-for="clubInfo.EmployeeID">
        <datalist id="staffList" >
            <option value="0">select...</option>
            @foreach(var person in Model.employeeList)
            {
                <option value="@person.EmployeeID" selected=@(Model.clubInfo != null && person.EmployeeID == Model.clubInfo.EmployeeID)>
                    @person.FirstName @person.LastName
                </option>
            }
        </select>
        <span asp-validation-for="clubInfo.EmployeeID"></span>
    </label>
    <label>
        Fee:
        <input type="number" asp-for="clubInfo.Fee" placeholder="0" step="1" min="0" />
        <span asp-validation-for="clubInfo.Fee"></span>
    </label>
    <label>
        Status(Active if checked):
        &nbsp
        <input type="checkbox" asp-for="clubInfo.Active" value="true" />
        <span asp-validation-for="clubInfo.Active"></span>
    </label>
    <br /><br />
    @if(Model.clubid != null)
    {
        //an existing staff
        <button type= "submit" asp-page-handler="New" disabled>Save New</button>
        <button type="submit" asp-page-handler="Update">Update</button>
        <button type="submit" asp-page-handler="Deactivate" formnovalidate onclick="return comfirm('Are you sure to deactivate this staff?')">Deactive</button>
    }
    else
    {
        //a new staff
        <button type= "submit" asp-page-handler="Insert" >Insert</button>
        <button type="submit" asp-page-handler="Update" disabled>Update</button>
        <button type="submit" asp-page-handler="Deactivate" formnovalidate disabled onclick="return comfirm('Are you sure to deactivate this staff?')">Deactive</button>
    }
    <button type="submit" asp-page-handler="Cancel" formnovalidate>Cancel</button>
</form>

WebAppA02/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">A02-Clubs</h1>
    <br /><br />
    <h2>Deliverable Descriptions</h2>
        <p>
            Query: Display the results of looking up Clubs by their active status (active/non-active). The employee drop-down has only employees active with clubs. Follow the mock-up below as a guide to displaying the results. Remember to include pagination.

            Each club line will contain a link to allow for record maintenance. This link will cause your CRUD page to appear. Add a separate New button to have your CRUD appear.
        </p>
        <p>
            CURD:Club entries are not deleted. Rather than providing a "delete" button, inlude a "Deactivate" button and in the BLL method, change the Active flag to false and update the database for that entry.
        </p>
    <br/><br/>
    <h2>Known Bugs</h2>
        <ul>
            <li>Unknown bug</li>
            <li>Unknown bug</li>
            <li>Unknown bug</li>
            <li>Unknown bug</li>
        </ul>
    <br /><br />
    <h2>Entity Relationship Diagram</h2>
        <img src="~/img/a02.png" alt="diagram">
    <br /><br />
    <h2>Site Styling Decision</h2>
    <a href="https://cdn.jsdelivr.net">cdn.jsdeliver.net/npm/holiday</a>
    @*<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>*@
</div>

WebAppA02/Pages/Query.cshtml
@page
@model WebAppA02.Pages.QueryModel
@{
    ViewData["Title"] = "Clubs By Status";
}
<h1>Clubs By Status</h1>

<form method="post">
    <div style="margin-bottom: 20px;">
        Select Club Status
        <div style="display: flex; gap: 20px; margin-bottom: 15px;">
            <div class="form-check">
                <input class="form-check-input" type="radio" id="Radio1" asp-for="clubStatus" value="Active" checked="true" />
                <label class="form-check-label" for="Radio1">
                    Active
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" id="Radio2" asp-for="clubStatus" value="In-Active" />
                <label class="form-check-label" for="Radio2">
                    In-Active
                </label>
            </div>
        </div>
        <button type="submit" asp-page-handler="Search">
                Search
        </button>
    </div>

    @if(Model.ClubList != null)
    {
        if(Model.EmployeeList.Count() == 0)
        {
            <p>This is an empty list</p>
        }
        else
        {
                <table class="table" style="height: 320px;">
                    <thead style="position: sticky; top: 0; z-index: 1; background: #f2f2f2;">
                        <th> </th>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Staff</th>
                        <th>Fee</th>
                        <th></th>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ClubList)
                        {

                            <tr>
                                <td><a href="./CRUD/@item.ClubID">Edit</a></td>
                                @*<td><a href="/Shared/CRUD?cid=@item.ClubID">Edit</a></td>*@
                                <td>@item.ClubID</td>
                                <td>@item.ClubName</td>
                                <td>
                                    <select>
                                    <option value="0" selected=@(item.EmployeeID == null) disabled=@(item.EmployeeID == null)>none</option>
                                        @foreach (var person in Model.EmployeeList)
                                        {
                                            <option value="@person.EmployeeID" selected=@(item.EmployeeID == person.EmployeeID)>@person.FirstName @person.LastName</option>
                                        }
                                    </select>
                                </td>
                                <td>@item.Fee</td>
                            </tr>

                        }
                    </tbody>
                </table>
@*            <nav aria-label="...">
                <ul class="pagination">
                    <li class="page-item disabled">
                        <button class="page-link" href="#" tabindex="-1">Previous</button>
                    </li>
                    @for (var i = 1; i <= Model.TotalPages; i++)
                    {
                        <li class="page-item @(Model.CurrentPage == i? "active": "")">
                            <a class="page-link" asp-for="SearchByPage(i)" href="#">@(i) <span class="sr-only">(current)</span></a>
                        </li>
                    }
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>*@
        }
    }
</form>